# _config.yml
title: Diário de um Engenheiro Cristão
email: fabio@example.com
description: "Reflexões de um engenheiro de software que acredita que excelência técnica é uma forma de adoração."
url: "https://fabio-ti.github.io"
baseurl: ""

# Remova ou comente estas linhas
 theme: minima
 plugins:
   - jekyll-feed
   - jekyll-sitemap

# Adicione isto
markdown: kramdown
permalink: pretty

# Autor
author: Fábio de Lima
