# _config.yml
title: Diário de um Engenheiro Cristão
email: fabio@example.com
description: >-
  Reflexões de um engenheiro de software que acredita que excelência técnica é uma forma de adoração.
baseurl: "/diario"
url: "https://fabio-ti.github.io"

# Jekyll
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Autor
author: Fábio de Lima
