# _config.yml
title: Diário de um Engenheiro Cristão
email: fabio@example.com
description: "Reflexões de um engenheiro de software que acredita que excelência técnica é uma forma de adoração."
url: "https://fabio-ti.github.io"
baseurl: ""

# Ative o tema minima
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Configuração
markdown: kramdown
permalink: pretty

# Autor
author: Fábio de Lima